# Generated by Django 6.1 on 2026-08-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
